[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
wastewise_solana = "5L9UbVeXGXwPh9xajNdySk3yGPqtX4dmpRUZiSb8B9kf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
